language: node_js
node_js:
- 9.8.0
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - dev
deploy:
  provider: pages
  local-dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: dev
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run test
after_success:
  - yarn run deploy
  - yarn run codeclimate
