language: node_js
node_js:
  - 9.8.0
sudo: false
cache:
  directories:
    - node_modules
branches:
  only:
    - dev
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: dev
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - npm install -g yarn
install:
  - yarn
script:
  - yarn run test
after_script:
  - yarn run deploy
after_success:
  - yarn run codeclimate
