language: node_js
node_js:
- 9.8.0
sudo: false
branches:
  only:
  - dev
public_repo: 40ce351805901ff0a3c87192bf4fb9d4a6233a36
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: 40ce351805901ff0a3c87192bf4fb9d4a6233a36
before_install:
- openssl aes-256-cbc -K $encrypted_782b3d36bc6b_key -iv $encrypted_782b3d36bc6b_iv
  -in SoraYama.enc -out ~\/.ssh/SoraYama -d
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
- npm install -g yarn
install:
- yarn
script:
- yarn run test
- yarn run deploy
after_script:
- yarn run codeclimate
